### ISSUE TITLE
errors in flask_react method

### ISSUE THREAD

**Issue by b3y0nd** [logan-markewich/llama_index_starter_pack#24]
I want to run the flask_react mode，when I run the launch_app.sh script，the error has happend:
(llama_index) ➜  flask_react git:(main) ✗ sh launch_app.sh            
index_server running...
initializing index...
server started...
 * Serving Flask app 'flask_demo'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5601
 * Running on http://10.226.20.147:5601
Press CTRL+C to quit

> llama_index_frontend@0.1.0 build
> react-scripts build

/home/wp/Desktop/llama_index_starter_pack/flask_react/node_modules/typescript/lib/typescript.js:139
    for (let i = startIndex ?? 0; i < array.length; i++) {
                             ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at getModules (/home/wp/Desktop/llama_index_starter_pack/flask_react/node_modules/react-scripts/config/modules.js:119:16)
    at Object.<anonymous> (/home/wp/Desktop/llama_index_starter_pack/flask_react/node_modules/react-scripts/config/modules.js:142:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

what does the solution about this? I'm not sure if this has anything to do with the npm version, my npm version is `8.5.1`
and react-scripts version is `5.0.1`

**Comment by b3y0nd** [comment]
Yeah, I have solved this quesion, if anyone else meet it ,try to run these commands diretly after you run `pip install -r requirements.txt`
* note that my computer OS is Ubuntu 22.04 desktop amd64
```
 3534  sudo apt install npm
 3562  whereis npm
 3578  npm i react-scripts  --no-fund --no-audit
 3584  sudo apt install nodejs
 3586  nodejs --version
 3588  node --version
 3589  sudo npm install n -g
 3590  sudo n stable
 3591  node --version
 3592  nodejs --version
 3596  npm list
 3605  npm install react-dom react --no-fund -no-audit
 3607  npm install web-vitals --no-fund -no-audit
 3609  npm install react-spinners --no-fund -no-audit
 3611  npm install classnames --no-fund -no-audit
 3613  npm install sass --no-fund -no-audit
 3616  npm install eslint-config-prettier --no-fund -no-audit
 3618  npm install eslint-plugin-prettier --no-fund -no-audit
 3621  npm i --save-dev @types/react --no-fund --no-audit
 3623  npm i --save-dev @testing-library/react --no-fund --no-audit
 3625  npm i --save-dev @types/jest --no-fund --no-audit
 3627  npm i --save-dev @testing-library/jest-dom --no-fund --no-audit
 3634  npm i serve --no-fund --no-audit
 3637  sudo npm install -g serve
```
